baseURL = "http://www.toursjug.org/"
languageCode = "fr-fr"
title = "Tours JUG"
# theme = "hugo-spectre-pixel-theme"
theme = "hugo-toursjug-theme"
buildFuture = true 
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687 - suppression des accents dans les URLs :)

[permalinks]
event = "/:section/:year:month:day/"


[params]
  name = "Tours JUG"

  events = "Nos évenements"
  about = "Qui sommes-nous"
  mailinglist = true
  mailinglist_text = "Pour ne manquer aucun des prochains evenement, inscrivez vous"
  blogTitle = "Les petits mots du JUG"

[test]
  show = true

