name = "ToursJUG Theme"
license = "MIT"
licenselink = "https://github.com/ToursJUG/hugo-toursjug-theme"
description = "Theme du site du ToursJUG"
homepage = "https://github.com/ToursJUG/hugo-toursjug-theme"
tags = ["ToursJUG"]
features = ["modern design", "timeline", "blog", "portfolio", "resume", "responsive", "pixel", "font awesome", "spectre css framework", "devicon", "google analytics", "rss", "syntax highlighting", "pagination"]
min_version = "0.01"

[author]
  name = "François Robert"
  homepage = "http://shisptone.org"

[original]
  # Inspired by Cactus theme
  name = "Cactus"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"
